In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

matplotlib.style.use('fivethirtyeight')
np.random.seed(113)

In [2]:
# loading csv file
df = pd.read_csv('../datasets/breast-cancer-wisconsin.data', names=['sample', 'thickness', 'size', 'shape', 'adhesion', 'epithelial', 'nuclei', 'chromatin', 'nucleoli', 'mitoses', 'status'], na_values='?')

print(df.isnull().sum())
df.head(10)

sample         0
thickness      0
size           0
shape          0
adhesion       0
epithelial     0
nuclei        16
chromatin      0
nucleoli       0
mitoses        0
status         0
dtype: int64


sample  thickness  size  shape  adhesion  epithelial  nuclei  chromatin  \
0  1000025          5     1      1         1           2     1.0          3   
1  1002945          5     4      4         5           7    10.0          3   
2  1015425          3     1      1         1           2     2.0          3   
3  1016277          6     8      8         1           3     4.0          3   
4  1017023          4     1      1         3           2     1.0          3   
5  1017122          8    10     10         8           7    10.0          9   
6  1018099          1     1      1         1           2    10.0          3   
7  1018561          2     1      2         1           2     1.0          3   
8  1033078          2     1      1         1           2     1.0          1   
9  1033078          4     2      1         1           2     1.0          2   

   nucleoli  mitoses  status  
0         1        1       2  
1         2        1       2  
2         1        1       2  
3         7        1       2  
4         1        1       2  
5         7        1       4  
6         1        1       2  
7         1        1       2  
8         1        5       2  
9         1        1       2

In [3]:
y = df['status']
X = df.drop(columns=['status', 'sample'])
# 'status' goes for labels and number of 'sample' isn't important

print(X.dtypes)
X.head(10)

thickness       int64
size            int64
shape           int64
adhesion        int64
epithelial      int64
nuclei        float64
chromatin       int64
nucleoli        int64
mitoses         int64
dtype: object


thickness  size  shape  adhesion  epithelial  nuclei  chromatin  nucleoli  \
0          5     1      1         1           2     1.0          3         1   
1          5     4      4         5           7    10.0          3         2   
2          3     1      1         1           2     2.0          3         1   
3          6     8      8         1           3     4.0          3         7   
4          4     1      1         3           2     1.0          3         1   
5          8    10     10         8           7    10.0          9         7   
6          1     1      1         1           2    10.0          3         1   
7          2     1      2         1           2     1.0          3         1   
8          2     1      1         1           2     1.0          1         1   
9          4     2      1         1           2     1.0          2         1   

   mitoses  
0        1  
1        1  
2        1  
3        1  
4        1  
5        1  
6        1  
7        1  
8        5  
9        1

In [4]:
# cleaning
X.fillna(X.mean(), inplace=True)
# changing NaN values for mean values

print(X.isna().sum())

# making correction of types
X['nuclei'] = X['nuclei'].astype('int64')
print(X.dtypes)
X.head(10)

thickness     0
size          0
shape         0
adhesion      0
epithelial    0
nuclei        0
chromatin     0
nucleoli      0
mitoses       0
dtype: int64
thickness     int64
size          int64
shape         int64
adhesion      int64
epithelial    int64
nuclei        int64
chromatin     int64
nucleoli      int64
mitoses       int64
dtype: object


thickness  size  shape  adhesion  epithelial  nuclei  chromatin  nucleoli  \
0          5     1      1         1           2       1          3         1   
1          5     4      4         5           7      10          3         2   
2          3     1      1         1           2       2          3         1   
3          6     8      8         1           3       4          3         7   
4          4     1      1         3           2       1          3         1   
5          8    10     10         8           7      10          9         7   
6          1     1      1         1           2      10          3         1   
7          2     1      2         1           2       1          3         1   
8          2     1      1         1           2       1          1         1   
9          4     2      1         1           2       1          2         1   

   mitoses  
0        1  
1        1  
2        1  
3        1  
4        1  
5        1  
6        1  
7        1  
8        5  
9        1

In [5]:
global n_dim
n_dim = 3

# declaration of perceptron class
class Perceptron():
    
    def __init__(self):
        self.weights = 2 * np.random.random((n_dim, 1)) - 1
        
    def ReLu(self, x):
        return (1 / (1 + np.exp(-x)))[0]
    
    def ReLu_derivative(self, x):
        return (x * (1 - x))[0]
    
    def perceptronComputing(self, inputs):
        inputs  = inputs.astype(float)
        outputs = self.ReLu(np.dot(inputs, self.weights))
        
        return outputs
    
    def train(self, inputs, outputs, n_iter=1000):
        
        for i in range(n_iter):
            results = self.perceptronComputing(inputs)
            error   = outputs - results
            adjustments  = np.dot(inputs.T, error * self.ReLu_derivative(results))
            #print(self.weights, adjustments.T) #(self.weights.T + 
            self.weights += adjustments.reshape(n_dim,1)

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

In [7]:
# preprocessing
preprocesser = StandardScaler()
preprocesser.fit(X)
X = preprocesser.transform(X)

# decomposition
pca = PCA(n_components=n_dim)
pca.fit(X)
X   = pca.transform(X)

In [8]:
perceptron = Perceptron()
print("Perceptron weights before training:\n", perceptron.weights)

y[y==2] = 0; y[y==4] = 1

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

perceptron.train(X_train, y_train, 1000)

Perceptron weights before training:
 [[ 0.70027189]
 [ 0.36838356]
 [-0.85554867]]


<ipython-input-8-9429fd3a6d1b>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[y==2] = 0; y[y==4] = 1


In [9]:
print("After training:\n", perceptron.weights)

After training:
 [[145.82218392]
 [ -5.06931354]
 [ -4.40642688]]


In [10]:
perceptron.perceptronComputing(X_test)

array([9.79280418e-85])